# Generated by Django 4.0.10 on 2024-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityblogpage_remove_activitystructurepage_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystructurepage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
