# Generated by Django 4.0.10 on 2024-06-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_achievementindexpage_achievementpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementpage',
            options={'verbose_name': 'Achievement Page', 'verbose_name_plural': 'Achievement Pages'},
        ),
    ]
