# Generated by Django 4.0.10 on 2024-06-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('course_name', models.CharField(max_length=255)),
                ('full_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.PositiveIntegerField(help_text='Общий объем занятий в часах')),
                ('description', models.TextField(help_text='Краткая запись о том, что будет освоено на курсе')),
                ('skills', models.TextField(help_text='Некоторые конкретные навыки')),
                ('contact_info', models.CharField(max_length=255)),
                ('program_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
