# Generated by Django 4.0.10 on 2024-06-05 17:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='description',
            field=models.TextField(blank=True, help_text='Краткая запись о том, что будет освоено на курсе'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='full_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='group_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='skills',
            field=models.TextField(blank=True, help_text='Некоторые конкретные навыки'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Общий объем занятий в часах', null=True),
        ),
        migrations.CreateModel(
            name='CourseGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='courses.coursepage')),
            ],
        ),
    ]
