# Generated by Django 4.0.10 on 2024-06-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('courses', '0002_alter_coursepage_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('club_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Краткая запись о том, что будет освоено в кружке')),
                ('contact_info', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
