# Generated by Django 4.0.10 on 2024-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_clubpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='full_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='group_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
