# Generated by Django 4.0.10 on 2024-06-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0007_studentinclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ActivityTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text="Bootstrap иконка, например 'bi bi-cpu-fill'", max_length=255)),
                ('background_color', models.CharField(help_text="Цвет фона в формате hex, например '#ecebff'", max_length=7)),
                ('icon_color', models.CharField(help_text="Цвет иконки в формате hex, например '#8660fe'", max_length=7)),
                ('link', models.URLField(help_text='Ссылка на деятельность')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='home.activityindexpage')),
            ],
        ),
    ]
