# Generated by Django 4.0.10 on 2024-06-05 15:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_activityindexpage_activitytile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytile',
            name='icon',
            field=models.CharField(help_text="Bootstrap иконка, например 'bi bi-cpu-fill", max_length=255),
        ),
        migrations.AlterField(
            model_name='activitytile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activitytile',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='home.activityindexpage'),
        ),
    ]
