# Generated by Django 4.0.10 on 2024-06-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_activitypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='activitytile',
            name='page',
        ),
        migrations.DeleteModel(
            name='ActivityIndexPage',
        ),
        migrations.DeleteModel(
            name='ActivityPage',
        ),
        migrations.DeleteModel(
            name='ActivityTile',
        ),
    ]
