# Generated by Django 4.0.10 on 2024-06-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='championshippage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='championshippage',
            name='documents',
        ),
    ]
