# Generated by Django 4.0.10 on 2024-06-13 16:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_remove_championshippage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='championshipparticipationpage',
            name='date_of_participation',
        ),
        migrations.RemoveField(
            model_name='championshipparticipationpage',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='championshipparticipationpage',
            name='result',
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год участия')),
                ('competence', models.CharField(max_length=255)),
                ('result', wagtail.fields.RichTextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='championships.championshippage')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
