# Generated by Django 4.0.10 on 2024-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_remove_championshippage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='championship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='result',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
