# Generated by Django 4.0.10 on 2024-06-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('championships', '0005_competence_participationyear_delete_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshippage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
