# Generated by Django 4.0.7 on 2023-02-05 10:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('html', wagtail.fields.StreamField([('HTML', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='specialtypage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())]))], blank=True, null=True, use_json_field=True, verbose_name='Фотографии слайдера'),
        ),
        migrations.CreateModel(
            name='ProfessionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('carousel', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())]))], blank=True, use_json_field=True, verbose_name='Фотографии слайдера')),
                ('time', models.CharField(blank=True, max_length=250, verbose_name='Сроки обучения')),
                ('p', wagtail.fields.RichTextField(blank=True, verbose_name='Текст описания')),
                ('html', wagtail.fields.StreamField([('HTML', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=None, verbose_name='Видео')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Учебная программа')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
